<script lang="ts">
	import { onMount, tick } from 'svelte';
	import { fade, slide } from 'svelte/transition';

	// --- Types ---
	type Column = { id: string; name: string; type: string; pk: boolean; nullable: boolean };
	type Table = { id: string; name: string; columns: Column[] };
	type Relationship = { 
		id: string;
		fromTable: string; 
		fromCol: string; 
		toTable: string; 
		toCol: string; 
		type: '1:1' | '1:N' | 'N:1';
	};

	// --- State ---
	let tables = $state<Table[]>([
		{
			id: '1',
			name: 'users',
			columns: [
				{ id: 'c1', name: 'id', type: 'INT', pk: true, nullable: false },
				{ id: 'c2', name: 'username', type: 'VARCHAR(255)', pk: false, nullable: false },
				{ id: 'c3', name: 'email', type: 'VARCHAR(255)', pk: false, nullable: false }
			]
		},
		{
			id: '2',
			name: 'posts',
			columns: [
				{ id: 'c4', name: 'id', type: 'INT', pk: true, nullable: false },
				{ id: 'c5', name: 'user_id', type: 'INT', pk: false, nullable: false },
				{ id: 'c6', name: 'title', type: 'TEXT', pk: false, nullable: false }
			]
		}
	]);

	let relationships = $state<Relationship[]>([
		{ id: 'r1', fromTable: 'posts', fromCol: 'user_id', toTable: 'users', toCol: 'id', type: 'N:1' }
	]);

	let activeTab = $state('designer'); // 'designer', 'sql', 'diagram'
	let sqlCode = $state('');
	let mermaidContainer: HTMLDivElement | undefined = $state();
	let isMermaidLoaded = $state(false);

	const sqlDataTypes = ['INT', 'BIGINT', 'SERIAL', 'VARCHAR(255)', 'TEXT', 'BOOLEAN', 'DATE', 'TIMESTAMP', 'DECIMAL(10,2)', 'UUID', 'JSONB'];

	// --- Helpers ---
	const generateId = () => Math.random().toString(36).substr(2, 9);

	function addTable() {
		const newId = generateId();
		tables = [...tables, {
			id: newId,
			name: `table_${tables.length + 1}`,
			columns: [{ id: generateId(), name: 'id', type: 'INT', pk: true, nullable: false }]
		}];
	}

	function removeTable(id: string) {
		const tableName = tables.find(t => t.id === id)?.name;
		tables = tables.filter(t => t.id !== id);
		// Cleanup relationships
		if (tableName) {
			relationships = relationships.filter(r => r.fromTable !== tableName && r.toTable !== tableName);
		}
	}

	function addColumn(tableId: string) {
		tables = tables.map(t => {
			if (t.id === tableId) {
				return {
					...t,
					columns: [...t.columns, { id: generateId(), name: 'new_col', type: 'VARCHAR(255)', pk: false, nullable: true }]
				};
			}
			return t;
		});
	}

	function removeColumn(tableId: string, colId: string) {
		tables = tables.map(t => {
			if (t.id === tableId) {
				const colName = t.columns.find(c => c.id === colId)?.name;
				if (colName) {
					relationships = relationships.filter(r => 
						!(r.fromTable === t.name && r.fromCol === colName) && 
						!(r.toTable === t.name && r.toCol === colName)
					);
				}
				return { ...t, columns: t.columns.filter(c => c.id !== colId) };
			}
			return t;
		});
	}

	function addRelationship() {
		if (tables.length < 2) return;
		relationships = [...relationships, {
			id: generateId(),
			fromTable: tables[tables.length - 1].name,
			fromCol: tables[tables.length - 1].columns[0].name,
			toTable: tables[0].name,
			toCol: tables[0].columns[0].name,
			type: 'N:1'
		}];
	}

	function removeRelationship(id: string) {
		relationships = relationships.filter(r => r.id !== id);
	}

	// --- SQL & Mermaid Logic ---
	function generateSQL() {
		let sql = '-- Generated by Database Designer Tool\n\n';
		
		tables.forEach(table => {
			sql += `CREATE TABLE ${table.name} (\n`;
			const colDefs = table.columns.map(col => {
				let def = `  ${col.name} ${col.type}`;
				if (col.pk) def += ' PRIMARY KEY';
				if (!col.nullable && !col.pk) def += ' NOT NULL';
				return def;
			});
			sql += colDefs.join(',\n');
			sql += '\n);\n\n';
		});

		relationships.forEach(rel => {
			sql += `ALTER TABLE ${rel.fromTable} \n  ADD CONSTRAINT fk_${rel.fromTable}_${rel.fromCol} \n  FOREIGN KEY (${rel.fromCol}) REFERENCES ${rel.toTable}(${rel.toCol});\n\n`;
		});

		sqlCode = sql;
	}

	function generateMermaid() {
		let mermaidValue = 'erDiagram\n';
		
		tables.forEach(table => {
			mermaidValue += `    ${table.name} {\n`;
			table.columns.forEach(col => {
				mermaidValue += `        ${col.type.replace(/\(.*\)/, '')} ${col.name} ${col.pk ? 'PK' : ''}\n`;
			});
			mermaidValue += `    }\n`;
		});

		relationships.forEach(rel => {
			const relSymbol = rel.type === '1:1' ? '|o--||' : (rel.type === '1:N' ? '||--o{' : '}o--||');
			mermaidValue += `    ${rel.fromTable} ${relSymbol} ${rel.toTable} : "references"\n`;
		});

		return mermaidValue;
	}

	async function renderDiagram() {
		if (!mermaidContainer || !isMermaidLoaded) return;
		const mermaid = (window as any).mermaid;
		const code = generateMermaid();
		
		try {
			const { svg } = await mermaid.render('db-diagram', code);
			if (mermaidContainer) mermaidContainer.innerHTML = svg;
		} catch (e) {
			console.error('Mermaid Render Error:', e);
		}
	}

	// Parsing (Basic Implementation)
	function parseSQL() {
		try {
			const newTables: Table[] = [];
			const newRels: Relationship[] = [];
			
			// Simple parser for CREATE TABLE
			const tableMatches = sqlCode.matchAll(/CREATE TABLE (\w+) \(([\s\S]*?)\);/gi);
			for (const match of tableMatches) {
				const tableName = match[1];
				const columnsBody = match[2];
				const columns: Column[] = [];
				
				columnsBody.split(',').forEach(line => {
					const parts = line.trim().split(/\s+/);
					if (parts.length >= 2) {
						columns.push({
							id: generateId(),
							name: parts[0],
							type: parts[1],
							pk: line.toUpperCase().includes('PRIMARY KEY'),
							nullable: !line.toUpperCase().includes('NOT NULL')
						});
					}
				});
				
				newTables.push({ id: generateId(), name: tableName, columns });
			}

			// Simple parser for ALTER TABLE (FK)
			const fkMatches = sqlCode.matchAll(/ALTER TABLE (\w+)[\s\S]*?FOREIGN KEY \((\w+)\) REFERENCES (\w+)\((\w+)\)/gi);
			for (const match of fkMatches) {
				newRels.push({
					id: generateId(),
					fromTable: match[1],
					fromCol: match[2],
					toTable: match[3],
					toCol: match[4],
					type: 'N:1'
				});
			}

			if (newTables.length > 0) {
				tables = newTables;
				relationships = newRels;
				activeTab = 'designer';
			}
		} catch (e) {
			alert('Lỗi khi phân tích SQL. Vui lòng kiểm tra định dạng standard CREATE TABLE.');
		}
	}

	onMount(() => {
		if (!(window as any).mermaid) {
			const script = document.createElement('script');
			script.src = 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js';
			script.onload = () => {
				(window as any).mermaid.initialize({ startOnLoad: false, theme: 'dark' });
				isMermaidLoaded = true;
				renderDiagram();
			};
			document.head.appendChild(script);
		} else {
			isMermaidLoaded = true;
			renderDiagram();
		}
	});

	$effect(() => {
		if (activeTab === 'sql') generateSQL();
		if (activeTab === 'diagram') renderDiagram();
	});

</script>

<div class="glass-panel w-full overflow-hidden rounded-[2.5rem] shadow-2xl p-1 relative min-h-[700px]">
	<div class="bg-surface/80 relative z-10 w-full rounded-[2.4rem] backdrop-blur-3xl p-6 sm:p-8 flex flex-col gap-8">
		
		<!-- Toolbar Tab Switcher -->
		<div class="flex flex-col sm:flex-row items-center justify-between gap-4 bg-white/60 dark:bg-black/40 p-4 rounded-3xl border-2 border-primary/40 backdrop-blur-md shadow-xl">
			<div class="flex items-center gap-1 p-1 bg-slate-300 dark:bg-white/10 rounded-2xl">
				<button 
					class="px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all {activeTab === 'designer' ? 'bg-white dark:bg-slate-800 text-primary shadow-md scale-105' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'}"
					onclick={() => activeTab = 'designer'}
				>
					Designer
				</button>
				<button 
					class="px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all {activeTab === 'diagram' ? 'bg-white dark:bg-slate-800 text-primary shadow-md scale-105' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'}"
					onclick={() => activeTab = 'diagram'}
				>
					Sơ đồ (ERD)
				</button>
				<button 
					class="px-6 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all {activeTab === 'sql' ? 'bg-white dark:bg-slate-800 text-primary shadow-md scale-105' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'}"
					onclick={() => activeTab = 'sql'}
				>
					SQL Code
				</button>
			</div>

			<div class="flex items-center gap-3">
				{#if activeTab === 'designer'}
					<button onclick={addTable} class="ui-btn ui-btn-primary !h-12 !px-6 !text-[0.8rem] gap-2 shadow-2xl shadow-primary/40 transition-all hover:scale-105 active:scale-95 font-black border-2 border-white/20">
						<span class="material-symbols-outlined text-xl">add_box</span> THÊM BẢNG
					</button>
					<button onclick={addRelationship} class="ui-btn bg-white dark:bg-slate-800 !h-12 !px-6 !text-[0.8rem] gap-2 border-2 border-primary/40 hover:bg-primary/10 transition-all font-black text-slate-900 dark:text-white">
						<span class="material-symbols-outlined text-xl">schema</span> QUAN HỆ
					</button>
				{:else if activeTab === 'sql'}
					<button onclick={parseSQL} class="ui-btn ui-btn-primary !h-12 !px-6 !text-[0.8rem] gap-2 shadow-2xl shadow-primary/40 transition-all hover:scale-105 active:scale-95 font-black border-2 border-white/20">
						<span class="material-symbols-outlined text-xl">sync_alt</span> ĐỒNG BỘ TỪ SQL
					</button>
				{/if}
			</div>
		</div>

		<!-- Content Areas -->
		<div class="flex-1 overflow-auto max-h-[1200px] custom-scrollbar">
			
			{#if activeTab === 'designer'}
				<div class="flex flex-col gap-10" in:fade>
					<!-- Tables Editor -->
					<div class="grid md:grid-cols-2 xl:grid-cols-3 gap-10">
						{#each tables as table (table.id)}
							<div class="bg-white dark:bg-slate-950/60 rounded-[3rem] border-2 border-primary/30 p-8 sm:p-10 flex flex-col gap-8 shadow-xl group hover:shadow-2xl hover:border-primary/60 transition-all duration-500 hover:-translate-y-2">
								<div class="flex justify-between items-center border-b-2 border-primary/20 pb-6">
									<div class="flex items-center gap-4">
										<span class="material-symbols-outlined text-primary text-3xl font-black">table_chart</span>
										<input 
											bind:value={table.name} 
											class="bg-transparent font-black tracking-tighter text-3xl outline-none focus:text-primary w-full text-slate-900 dark:text-white"
											placeholder="Table name"
										/>
									</div>
									<button 
										onclick={() => removeTable(table.id)} 
										class="size-12 flex items-center justify-center rounded-2xl bg-red-50 dark:bg-red-500/10 text-red-500 hover:bg-red-500 hover:text-white transition-all active:scale-90 shadow-md border border-red-200 dark:border-red-500/20"
										title="Remove Table"
									>
										<span class="material-symbols-outlined text-2xl font-bold">delete_forever</span>
									</button>
								</div>
								
								<div class="flex flex-col gap-5">
									{#each table.columns as col (col.id)}
										<div class="flex items-center gap-4 p-4 rounded-2xl bg-slate-100 dark:bg-white/5 border-2 border-slate-200 dark:border-white/10 group/col hover:border-primary/60 transition-all">
											<input bind:value={col.name} class="bg-transparent font-black text-base w-full outline-none text-slate-900 dark:text-slate-100" />
											<select bind:value={col.type} class="bg-transparent outline-none max-w-[120px] font-mono text-[0.7rem] font-black text-primary uppercase cursor-pointer">
												{#each sqlDataTypes as type}
													<option value={type}>{type}</option>
												{/each}
											</select>
											<div class="flex items-center gap-2">
												<button 
													onclick={() => col.pk = !col.pk} 
													class="{col.pk ? 'text-amber-500 scale-125' : 'text-slate-400 dark:text-slate-600'} transition-all hover:text-amber-400"
													title="Primary Key"
												>
													<span class="material-symbols-outlined text-xl font-bold">vpn_key</span>
												</button>
												<button onclick={() => removeColumn(table.id, col.id)} class="text-slate-300 hover:text-red-500 transition-colors">
													<span class="material-symbols-outlined text-xl">cancel</span>
												</button>
											</div>
										</div>
									{/each}
								</div>

								<button onclick={() => addColumn(table.id)} class="text-[0.75rem] font-black uppercase text-primary tracking-[0.2em] flex items-center justify-center gap-2 p-4 rounded-2xl border-2 border-dashed border-primary/30 hover:border-primary hover:bg-primary/5 transition-all">
									<span class="material-symbols-outlined text-xl">add_circle</span> THÊM CỘT
								</button>
							</div>
						{/each}
					</div>

					<!-- Relationships Editor -->
					{#if relationships.length > 0}
						<div class="bg-primary/5 rounded-[3.5rem] p-10 border-2 border-primary/30 shadow-inner">
							<h3 class="text-[0.8rem] font-black uppercase tracking-[0.3em] text-primary mb-8 flex items-center gap-3">
								<span class="material-symbols-outlined text-2xl">hub</span>
								MỐI QUAN HỆ HỆ THỐNG (FK)
							</h3>
							<div class="grid gap-6">
								{#each relationships as rel (rel.id)}
									<div class="flex flex-wrap items-center gap-6 bg-white dark:bg-black/60 p-6 rounded-[2rem] text-[0.9rem] font-black shadow-xl border-2 border-primary/20">
										<div class="flex items-center gap-3 px-5 py-2 bg-slate-100 dark:bg-white/5 rounded-xl border-2 border-slate-200 dark:border-white/10">
											<select bind:value={rel.fromTable} class="bg-transparent outline-none text-slate-900 dark:text-white">
												{#each tables as t}<option value={t.name}>{t.name}</option>{/each}
											</select>
											<span class="text-primary font-black">→</span>
											<select bind:value={rel.fromCol} class="bg-transparent text-primary outline-none">
												{#each (tables.find(t => t.name === rel.fromTable)?.columns || []) as c}
													<option value={c.name}>{c.name}</option>
												{/each}
											</select>
										</div>
										
										<div class="px-6 py-2 bg-primary text-white rounded-full text-[0.7rem] font-black shadow-xl shadow-primary/30 border-2 border-white/20">
											<select bind:value={rel.type} class="bg-transparent outline-none uppercase tracking-widest">
												<option value="1:1">ONE TO ONE</option>
												<option value="1:N">ONE TO MANY</option>
												<option value="N:1">MANY TO ONE</option>
											</select>
										</div>

										<span class="text-[0.7rem] font-black uppercase tracking-widest text-slate-400">REFERENCES</span>

										<div class="flex items-center gap-3 px-5 py-2 bg-emerald-500/5 rounded-xl border-2 border-emerald-500/30">
											<select bind:value={rel.toTable} class="bg-transparent outline-none text-emerald-600 dark:text-emerald-400">
												{#each tables as t}<option value={t.name}>{t.name}</option>{/each}
											</select>
											<span class="text-emerald-500 font-black">.</span>
											<select bind:value={rel.toCol} class="bg-transparent outline-none text-emerald-600 dark:text-emerald-400">
												{#each (tables.find(t => t.name === rel.toTable)?.columns || []) as c}
													<option value={c.name}>{c.name}</option>
												{/each}
											</select>
										</div>

										<button onclick={() => removeRelationship(rel.id)} class="ml-auto size-12 flex items-center justify-center rounded-2xl bg-red-50 dark:bg-red-500/10 text-red-500 hover:bg-red-500 hover:text-white transition-all shadow-md border border-red-200 dark:border-red-500/20">
											<span class="material-symbols-outlined text-2xl">link_off</span>
										</button>
									</div>
								{/each}
							</div>
						</div>
					{/if}
				</div>

			{:else if activeTab === 'diagram'}
				<div class="flex flex-col items-center justify-center min-h-[600px]" in:fade>
					{#if tables.length === 0}
						<div class="text-center opacity-40">
							<span class="material-symbols-outlined text-[8rem] text-primary">analytics</span>
							<p class="mt-8 font-black tracking-[0.4em] uppercase text-sm">Chưa có kiến trúc để hiển thị sơ đồ</p>
						</div>
					{:else}
						<div bind:this={mermaidContainer} class="w-full h-full flex items-center justify-center p-10 bg-white/40 dark:bg-black/20 rounded-[3rem] border-2 border-primary/20 overflow-auto shadow-inner"></div>
					{/if}
				</div>

			{:else if activeTab === 'sql'}
				<div class="flex flex-col gap-10 h-full" in:fade>
					<div class="relative group">
						<div class="absolute -inset-2 bg-gradient-to-r from-primary/40 to-blue-600/40 blur-xl opacity-100 transition duration-1000 group-hover:duration-200"></div>
						<textarea 
							bind:value={sqlCode} 
							class="relative w-full h-[850px] bg-slate-950/95 backdrop-blur-3xl text-blue-50 p-12 font-mono text-lg rounded-[3rem] border-2 border-white/30 outline-none focus:ring-8 focus:ring-primary/20 transition-all custom-scrollbar leading-relaxed shadow-2xl"
							spellcheck="false"
						></textarea>
						<button 
							onclick={() => {
								navigator.clipboard.writeText(sqlCode);
								alert('Copied to clipboard!');
							}}
							class="absolute top-10 right-10 bg-white/10 hover:bg-primary backdrop-blur-2xl text-white px-8 py-4 rounded-3xl text-[0.8rem] font-black uppercase tracking-[0.2em] transition-all border-2 border-white/30 shadow-2xl active:scale-95 flex items-center gap-3"
						>
							<span class="material-symbols-outlined text-2xl font-bold">content_copy</span>
							COPY SQL OUTPUT
						</button>
					</div>
					<div class="p-8 bg-white dark:bg-slate-900 border-2 border-primary/40 rounded-[3rem] flex gap-8 items-center shadow-2xl">
						<div class="size-20 rounded-[2rem] bg-primary/20 flex items-center justify-center shrink-0 border-2 border-primary/30">
							<span class="material-symbols-outlined text-primary text-5xl font-black">tips_and_updates</span>
						</div>
						<div class="flex flex-col gap-2">
							<h4 class="text-primary font-black uppercase tracking-[0.3em] text-sm">Hướng dẫn Năng Suất</h4>
							<p class="text-[1rem] text-slate-700 dark:text-slate-300 leading-relaxed font-bold">
								Bạn có thể dán mã SQL trực tiếp vào đây, sau đó bấm <span class="px-4 py-1.5 rounded-xl bg-primary text-white text-[0.75rem] font-black mx-1 shadow-xl uppercase border border-white/20">ĐỒNG BỘ TỪ SQL</span> ở trên để dựng lại toàn bộ cấu trúc thiết kế và sơ đồ ERD ngay lập tức.
							</p>
						</div>
					</div>
				</div>
			{/if}

		</div>
	</div>

	<div class="absolute -right-20 -top-20 size-80 rounded-full bg-primary/5 blur-[100px] pointer-events-none"></div>
</div>

<style>
	.custom-scrollbar::-webkit-scrollbar {
		width: 10px;
		height: 10px;
	}
	.custom-scrollbar::-webkit-scrollbar-thumb {
		background-color: var(--ui-primary);
		border: 2px solid transparent;
		background-clip: padding-box;
		border-radius: 9999px;
	}

	:global(.db-diagram) {
		max-width: 100%;
	}
</style>
