export type Column = {
	id: string;
	name: string;
	type: string;
	pk: boolean;
	nullable: boolean;
};

export type Table = {
	id: string;
	name: string;
	columns: Column[];
};

export type RelationshipType = '1:1' | '1:N' | 'N:1';

export type Relationship = {
	id: string;
	fromTableId: string;
	fromColumnId: string;
	toTableId: string;
	toColumnId: string;
	type: RelationshipType;
};

export type DesignerTab = 'designer' | 'sql' | 'diagram';

export type DesignerDraftState = {
	tables: Table[];
	relationships: Relationship[];
	activeTab: DesignerTab;
	sqlCode: string;
};

export const SQL_DATA_TYPES = [
	'INT',
	'BIGINT',
	'SERIAL',
	'VARCHAR(255)',
	'TEXT',
	'BOOLEAN',
	'DATE',
	'TIMESTAMP',
	'DECIMAL(10,2)',
	'UUID',
	'JSONB'
] as const;

const RESERVED_SQL_COLUMN_PREFIXES = new Set(['PRIMARY', 'FOREIGN', 'CONSTRAINT', 'UNIQUE', 'CHECK']);

export function createId(): string {
	if (typeof globalThis.crypto?.randomUUID === 'function') {
		return globalThis.crypto.randomUUID();
	}

	return `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export function cloneColumn(column: Column): Column {
	return { ...column };
}

export function cloneTable(table: Table): Table {
	return {
		...table,
		columns: table.columns.map(cloneColumn)
	};
}

export function cloneRelationship(relationship: Relationship): Relationship {
	return { ...relationship };
}

export function cloneDraftState(state: DesignerDraftState): DesignerDraftState {
	return {
		tables: state.tables.map(cloneTable),
		relationships: state.relationships.map(cloneRelationship),
		activeTab: state.activeTab,
		sqlCode: state.sqlCode
	};
}

export function isDesignerTab(value: unknown): value is DesignerTab {
	return value === 'designer' || value === 'sql' || value === 'diagram';
}

export function getTableById(tables: Table[], tableId: string): Table | undefined {
	return tables.find((table) => table.id === tableId);
}

export function getColumnById(table: Table | undefined, columnId: string): Column | undefined {
	return table?.columns.find((column) => column.id === columnId);
}

export function getColumnsForTable(tables: Table[], tableId: string): Column[] {
	return getTableById(tables, tableId)?.columns ?? [];
}

export function getTableName(tables: Table[], tableId: string): string {
	return getTableById(tables, tableId)?.name ?? 'unknown_table';
}

export function getColumnName(tables: Table[], tableId: string, columnId: string): string {
	return getColumnById(getTableById(tables, tableId), columnId)?.name ?? 'unknown_column';
}

export function sanitizeRelationships(tables: Table[], relationships: Relationship[]): Relationship[] {
	return relationships.filter((relationship) => {
		const fromTable = getTableById(tables, relationship.fromTableId);
		const toTable = getTableById(tables, relationship.toTableId);
		if (!fromTable || !toTable) return false;

		const fromColumn = getColumnById(fromTable, relationship.fromColumnId);
		const toColumn = getColumnById(toTable, relationship.toColumnId);
		return Boolean(fromColumn && toColumn);
	});
}

export function generateSqlFromSchema(tables: Table[], relationships: Relationship[]): string {
	let sql = '-- Generated by Database Designer Tool\n\n';

	for (const table of tables) {
		sql += `CREATE TABLE ${table.name} (\n`;

		const columnDefinitions = table.columns.map((column) => {
			let definition = `  ${column.name} ${column.type}`;

			if (column.pk) definition += ' PRIMARY KEY';
			if (!column.nullable && !column.pk) definition += ' NOT NULL';

			return definition;
		});

		sql += columnDefinitions.join(',\n');
		sql += '\n);\n\n';
	}

	for (const relationship of sanitizeRelationships(tables, relationships)) {
		const fromTableName = getTableName(tables, relationship.fromTableId);
		const toTableName = getTableName(tables, relationship.toTableId);
		const fromColumnName = getColumnName(tables, relationship.fromTableId, relationship.fromColumnId);
		const toColumnName = getColumnName(tables, relationship.toTableId, relationship.toColumnId);

		sql += `ALTER TABLE ${fromTableName} \n`;
		sql += `  ADD CONSTRAINT fk_${fromTableName}_${fromColumnName} \n`;
		sql += `  FOREIGN KEY (${fromColumnName}) REFERENCES ${toTableName}(${toColumnName});\n\n`;
	}

	return sql;
}

export function generateMermaidFromSchema(tables: Table[], relationships: Relationship[]): string {
	let mermaidCode = 'erDiagram\n';

	for (const table of tables) {
		mermaidCode += `    ${table.name} {\n`;

		for (const column of table.columns) {
			mermaidCode += `        ${column.type.replace(/\(.*\)/, '')} ${column.name} ${column.pk ? 'PK' : ''}\n`;
		}

		mermaidCode += '    }\n';
	}

	for (const relationship of sanitizeRelationships(tables, relationships)) {
		const relationSymbol = relationship.type === '1:1'
			? '|o--||'
			: relationship.type === '1:N'
				? '||--o{'
				: '}o--||';

		mermaidCode += `    ${getTableName(tables, relationship.fromTableId)} ${relationSymbol} ${getTableName(tables, relationship.toTableId)} : "references"\n`;
	}

	return mermaidCode;
}

export function createDefaultDraftState(): DesignerDraftState {
	const userTableId = createId();
	const postTableId = createId();
	const userIdColumnId = createId();
	const usernameColumnId = createId();
	const emailColumnId = createId();
	const postIdColumnId = createId();
	const postUserIdColumnId = createId();
	const postTitleColumnId = createId();

	const tables: Table[] = [
		{
			id: userTableId,
			name: 'users',
			columns: [
				{ id: userIdColumnId, name: 'id', type: 'INT', pk: true, nullable: false },
				{ id: usernameColumnId, name: 'username', type: 'VARCHAR(255)', pk: false, nullable: false },
				{ id: emailColumnId, name: 'email', type: 'VARCHAR(255)', pk: false, nullable: false }
			]
		},
		{
			id: postTableId,
			name: 'posts',
			columns: [
				{ id: postIdColumnId, name: 'id', type: 'INT', pk: true, nullable: false },
				{ id: postUserIdColumnId, name: 'user_id', type: 'INT', pk: false, nullable: false },
				{ id: postTitleColumnId, name: 'title', type: 'TEXT', pk: false, nullable: false }
			]
		}
	];

	const relationships: Relationship[] = [
		{
			id: createId(),
			fromTableId: postTableId,
			fromColumnId: postUserIdColumnId,
			toTableId: userTableId,
			toColumnId: userIdColumnId,
			type: 'N:1'
		}
	];

	return {
		tables,
		relationships,
		activeTab: 'designer',
		sqlCode: generateSqlFromSchema(tables, relationships)
	};
}

export function addTable(tables: Table[]): Table[] {
	return [
		...tables,
		{
			id: createId(),
			name: `table_${tables.length + 1}`,
			columns: [
				{
					id: createId(),
					name: 'id',
					type: 'INT',
					pk: true,
					nullable: false
				}
			]
		}
	];
}

export function removeTable(
	tables: Table[],
	relationships: Relationship[],
	tableId: string
): { tables: Table[]; relationships: Relationship[] } {
	return {
		tables: tables.filter((table) => table.id !== tableId),
		relationships: relationships.filter(
			(relationship) => relationship.fromTableId !== tableId && relationship.toTableId !== tableId
		)
	};
}

export function addColumn(tables: Table[], tableId: string): Table[] {
	return tables.map((table) => {
		if (table.id !== tableId) return table;

		return {
			...table,
			columns: [
				...table.columns,
				{
					id: createId(),
					name: 'new_col',
					type: 'VARCHAR(255)',
					pk: false,
					nullable: true
				}
			]
		};
	});
}

export function removeColumn(
	tables: Table[],
	relationships: Relationship[],
	tableId: string,
	columnId: string
): { tables: Table[]; relationships: Relationship[] } {
	return {
		tables: tables.map((table) => {
			if (table.id !== tableId) return table;

			return {
				...table,
				columns: table.columns.filter((column) => column.id !== columnId)
			};
		}),
		relationships: relationships.filter(
			(relationship) =>
				!(
					(relationship.fromTableId === tableId && relationship.fromColumnId === columnId) ||
					(relationship.toTableId === tableId && relationship.toColumnId === columnId)
				)
		)
	};
}

export function addRelationship(tables: Table[], relationships: Relationship[]): Relationship[] {
	if (tables.length < 2) return relationships;

	const fromTable = tables[tables.length - 1];
	const toTable = tables[0];
	const fromColumn = fromTable.columns[0];
	const toColumn = toTable.columns[0];

	if (!fromColumn || !toColumn) return relationships;

	return [
		...relationships,
		{
			id: createId(),
			fromTableId: fromTable.id,
			fromColumnId: fromColumn.id,
			toTableId: toTable.id,
			toColumnId: toColumn.id,
			type: 'N:1'
		}
	];
}

export function removeRelationship(relationships: Relationship[], relationshipId: string): Relationship[] {
	return relationships.filter((relationship) => relationship.id !== relationshipId);
}

function splitSqlDefinitions(columnsBody: string): string[] {
	const definitions: string[] = [];
	let current = '';
	let depth = 0;

	for (const character of columnsBody) {
		if (character === '(') depth += 1;
		if (character === ')') depth = Math.max(0, depth - 1);

		if (character === ',' && depth === 0) {
			const trimmed = current.trim();
			if (trimmed) definitions.push(trimmed);
			current = '';
			continue;
		}

		current += character;
	}

	const trimmed = current.trim();
	if (trimmed) definitions.push(trimmed);

	return definitions;
}

export function parseSqlToSchema(sqlCode: string): { tables: Table[]; relationships: Relationship[] } {
	const tables: Table[] = [];
	const relationships: Relationship[] = [];
	const tableIdByName = new Map<string, string>();
	const columnsByTableAndName = new Map<string, string>();

	const tableMatches = sqlCode.matchAll(/CREATE TABLE (\w+) \(([\s\S]*?)\);/gi);

	for (const match of tableMatches) {
		const tableName = match[1];
		const columnsBody = match[2];
		const tableId = createId();
		const columns: Column[] = [];

		for (const line of splitSqlDefinitions(columnsBody)) {
			const normalizedLine = line.trim();
			if (!normalizedLine) continue;

			const parts = normalizedLine.split(/\s+/);
			if (parts.length < 2) continue;
			if (RESERVED_SQL_COLUMN_PREFIXES.has(parts[0].toUpperCase())) continue;

			const column: Column = {
				id: createId(),
				name: parts[0],
				type: parts[1],
				pk: normalizedLine.toUpperCase().includes('PRIMARY KEY'),
				nullable: !normalizedLine.toUpperCase().includes('NOT NULL')
			};

			if (column.pk) {
				column.nullable = false;
			}

			columns.push(column);
			columnsByTableAndName.set(`${tableName}.${column.name}`, column.id);
		}

		tables.push({
			id: tableId,
			name: tableName,
			columns
		});

		tableIdByName.set(tableName, tableId);
	}

	const fkMatches = sqlCode.matchAll(
		/ALTER TABLE (\w+)[\s\S]*?FOREIGN KEY \((\w+)\) REFERENCES (\w+)\((\w+)\)/gi
	);

	for (const match of fkMatches) {
		const fromTableName = match[1];
		const fromColumnName = match[2];
		const toTableName = match[3];
		const toColumnName = match[4];
		const fromTableId = tableIdByName.get(fromTableName);
		const toTableId = tableIdByName.get(toTableName);
		const fromColumnId = columnsByTableAndName.get(`${fromTableName}.${fromColumnName}`);
		const toColumnId = columnsByTableAndName.get(`${toTableName}.${toColumnName}`);

		if (!fromTableId || !toTableId || !fromColumnId || !toColumnId) continue;

		relationships.push({
			id: createId(),
			fromTableId,
			fromColumnId,
			toTableId,
			toColumnId,
			type: 'N:1'
		});
	}

	return {
		tables,
		relationships
	};
}
